# Generated by Django 3.0.3 on 2022-10-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modaliti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, verbose_name='Modaliti')),
                ('singkatan', models.CharField(max_length=50, verbose_name='Singkatan')),
                ('detail', models.CharField(blank=True, max_length=250, null=True, verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Modaliti',
                'verbose_name_plural': 'Modaliti',
                'ordering': ['nama'],
            },
        ),
    ]
