# Generated by Django 4.2.6 on 2023-10-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='cd',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='lmp',
            field=models.DateField(blank=True, null=True, verbose_name='LMP'),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='laterality',
            field=models.CharField(blank=True, choices=[('Kiri', 'Kiri'), ('Kanan', 'Kanan')], max_length=10, null=True),
        ),
    ]
