# Generated by Django 3.0.3 on 2022-10-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaliti',
            name='singkatan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Singkatan'),
        ),
    ]
