# Generated by Django 4.1.2 on 2023-01-12 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wad', '0006_alter_disiplin_disiplin'),
        ('exam', '0002_auto_20221004_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', models.DateTimeField(default=django.utils.timezone.now)),
                ('mrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='MRN')),
                ('nric', models.CharField(blank=True, help_text='NRIC / Passport Jika Tiada AM', max_length=25, null=True, verbose_name='NRIC')),
                ('nama', models.CharField(max_length=30, null=True)),
                ('pemohon', models.CharField(max_length=30, null=True)),
                ('mo', models.CharField(blank=True, help_text='MO Radiologi', max_length=30, null=True, verbose_name='MO')),
                ('radiologist', models.CharField(blank=True, max_length=30, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('jxr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wad.ward')),
            ],
            options={
                'verbose_name_plural': 'BCS',
                'ordering': ['-tarikh'],
                'unique_together': {('tarikh', 'mrn', 'nric')},
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=50)),
                ('catatan', models.CharField(blank=True, max_length=200, null=True)),
                ('contrast', models.BooleanField(default=False)),
                ('modaliti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.modaliti')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.part')),
            ],
            options={
                'verbose_name_plural': 'Pemeriksaan',
                'ordering': ['modaliti', 'part', 'exam'],
                'unique_together': {('exam', 'part', 'modaliti')},
            },
        ),
        migrations.CreateModel(
            name='Daftar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nobcs', models.CharField(blank=True, max_length=20, null=True, verbose_name='No. BCS')),
                ('laterality', models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right')], max_length=10, null=True)),
                ('merged', models.BooleanField(default=False)),
                ('dcatatan', models.CharField(blank=True, max_length=20, null=True, verbose_name='Catatan')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bcs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.bcs')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('jxr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pendaftaran BCS',
                'ordering': ['nobcs'],
            },
        ),
    ]
