# Generated by Django 4.2.6 on 2023-10-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_daftar_cd_alter_daftar_lmp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar',
            name='performed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daftar',
            name='status',
            field=models.CharField(default='Performed', max_length=15),
        ),
    ]
