# Generated by Django 4.2.6 on 2023-10-15 23:24

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wad', '0001_initial'),
        ('exam', '0004_alter_daftar_pemohon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='rujukan',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wad.ward'),
        ),
    ]
