# Generated by Django 4.1.2 on 2023-01-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_daftar_jxr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.part'),
        ),
    ]
