# Generated by Django 4.2.6 on 2023-10-22 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_daftar_rujukan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='performed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Performed', 'Performed'), ('Completed', 'Completed')], default='Performed', max_length=15),
        ),
    ]
