# Generated by Django 4.1.2 on 2023-01-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_exam_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
