# Generated by Django 4.2.6 on 2023-10-23 03:32

import auto_prefetch
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0006_alter_daftar_performed_alter_daftar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='jxr',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bcs_jxr', to=settings.AUTH_USER_MODEL, verbose_name='Juru X-Ray'),
        ),
    ]
