# Generated by Django 4.2.6 on 2023-11-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_daftar_jxr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftar',
            name='cd',
        ),
        migrations.RemoveField(
            model_name='daftar',
            name='filem',
        ),
        migrations.AddField(
            model_name='daftar',
            name='hamil',
            field=models.BooleanField(default=False),
        ),
    ]
