# Generated by Django 4.2.6 on 2023-11-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_daftar_cd_remove_daftar_filem_daftar_hamil'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaan',
            name='kv',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='kVp'),
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='mas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mAs'),
        ),
    ]
