# Generated by Django 4.1.2 on 2023-01-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wad', '0006_alter_disiplin_disiplin'),
        ('exam', '0008_alter_daftar_jxr_alter_daftar_merge_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcs',
            name='pemohon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bcs',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wad.ward'),
        ),
    ]
