# Generated by Django 4.2.6 on 2024-01-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_pemeriksaan_mgy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='pemohon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
