# Generated by Django 4.1.2 on 2023-01-28 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_exam_statistik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, help_text='Region/Bahagian untuk Statistik', max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Statistik Region',
                'ordering': ['nama'],
            },
        ),
        migrations.AlterField(
            model_name='exam',
            name='statistik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.region'),
        ),
    ]
