# Generated by Django 4.1.2 on 2023-01-29 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_region_alter_exam_statistik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.part'),
        ),
    ]
