# Generated by Django 4.2.6 on 2024-03-16 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_daftar_pemohon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacsExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orthanc_id', models.CharField(blank=True, max_length=100, null=True)),
                ('study_id', models.CharField(blank=True, max_length=100, null=True)),
                ('study_instance', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.pemeriksaan')),
            ],
            options={
                'verbose_name_plural': 'Pacs Item',
            },
        ),
    ]
