# Generated by Django 4.1.2 on 2023-02-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0012_alter_exam_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="short_desc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="status_ca",
            field=models.CharField(
                choices=[("ENABLE", "Enable"), ("DISABLE", "Disable")],
                default="ENABLE",
                max_length=10,
            ),
        ),
    ]
