# Generated by Django 4.2.6 on 2025-01-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_pacsexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orthancurl', models.URLField(verbose_name='Orthanc URL')),
                ('viewrurl', models.URLField(verbose_name='DICOM Viewer URL')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PACS Configuration',
                'verbose_name_plural': 'PACS Configurations',
            },
        ),
    ]
