# Generated by Django 4.1.2 on 2023-02-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0013_exam_short_desc_exam_status_ca"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={"ordering": ["order"], "verbose_name_plural": "Statistik Region"},
        ),
        migrations.AddField(
            model_name="region",
            name="bahagian",
            field=models.CharField(
                blank=True,
                help_text="Bahagian untuk Statistik",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="jenis",
            field=models.CharField(
                blank=True,
                help_text="Modaliti untuk Statistik",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together={("jenis", "bahagian")},
        ),
        migrations.RemoveField(
            model_name="region",
            name="nama",
        ),
    ]
