# Generated by Django 4.2.6 on 2025-07-26 09:32

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_daftar_accession_number_daftar_modality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='daftar',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemeriksaan', to='exam.daftar'),
        ),
    ]
