# Generated by Django 4.2.6 on 2025-07-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_alter_pemeriksaan_daftar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaan',
            name='catatan',
            field=models.CharField(blank=True, help_text='Catatan khusus untuk pemeriksaan ini (contoh: pesakit tidak dapat luruskan jari)', max_length=200, null=True, verbose_name='Catatan'),
        ),
    ]
