# Generated by Django 4.2.6 on 2025-07-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_pemeriksaan_catatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftar',
            name='dcatatan',
        ),
        migrations.RemoveField(
            model_name='daftar',
            name='performed',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_code',
        ),
        migrations.AddField(
            model_name='daftar',
            name='parent_accession_number',
            field=models.CharField(blank=True, help_text='Parent accession number for grouped studies (e.g., KKP2025XR0000001)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='daftar',
            name='requested_procedure_id',
            field=models.CharField(blank=True, help_text='DICOM Requested Procedure ID (maps 1-to-1 with parent_accession_number)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='daftar',
            name='study_description',
            field=models.CharField(blank=True, help_text="Description of the study (e.g., 'XR Series')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daftar',
            name='study_status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', help_text='Overall study status', max_length=15),
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='accession_number',
            field=models.CharField(blank=True, help_text='Individual accession number for this examination (e.g., KKP202500000001)', max_length=20, null=True, verbose_name='Accession Number'),
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='body_position',
            field=models.CharField(blank=True, choices=[('ERECT', 'Erect/Standing'), ('SUPINE', 'Supine'), ('PRONE', 'Prone'), ('DECUBITUS_LEFT', 'Left Decubitus'), ('DECUBITUS_RIGHT', 'Right Decubitus')], help_text='Body position during examination', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='exam_status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', help_text='Individual examination status', max_length=15),
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='patient_position',
            field=models.CharField(blank=True, choices=[('AP', 'Anterior-Posterior'), ('PA', 'Posterior-Anterior'), ('LAT', 'Lateral'), ('LATERAL_LEFT', 'Left Lateral'), ('LATERAL_RIGHT', 'Right Lateral'), ('OBLIQUE', 'Oblique')], help_text='Patient position for X-ray (AP/PA/Lateral)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='scheduled_step_id',
            field=models.CharField(blank=True, help_text='DICOM Scheduled Procedure Step ID (maps to accession_number)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='sequence_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Order of this examination within the study'),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='accession_number',
            field=models.CharField(blank=True, help_text='Legacy accession number field (use parent_accession_number for new studies)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='no_xray',
            field=models.CharField(blank=True, help_text='Legacy X-ray number field (use accession_number for new examinations)', max_length=20, null=True, verbose_name='No. X-Ray (Legacy)'),
        ),
    ]
