# Generated by Django 4.2.6 on 2025-07-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_remove_daftar_dcatatan_remove_daftar_performed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacsconfig',
            name='endpoint_style',
            field=models.CharField(choices=[('dicomweb', 'DICOMweb (OHIF-style) - Standard WADO-RS'), ('file', 'File endpoint - Direct Orthanc /file'), ('attachment', 'Attachment - Raw DICOM data'), ('auto', 'Auto-detect - Try best working endpoint')], default='dicomweb', help_text='Choose which Orthanc endpoint style to use for DICOM image retrieval', max_length=20, verbose_name='Endpoint Style'),
        ),
    ]
