# Generated by Django 4.2.6 on 2025-07-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_pacsconfig_endpoint_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_root_paths', models.JSONField(default=list, help_text='List of storage paths to monitor for capacity and usage analysis')),
                ('storage_warning_threshold', models.PositiveIntegerField(default=80, help_text='Storage usage percentage that triggers warning alerts')),
                ('storage_critical_threshold', models.PositiveIntegerField(default=90, help_text='Storage usage percentage that triggers critical alerts')),
                ('target_turnaround_time', models.PositiveIntegerField(default=60, help_text='Target turnaround time in minutes from registration to completion')),
                ('target_daily_throughput', models.PositiveIntegerField(default=50, help_text='Target number of examinations per day')),
                ('target_equipment_utilization', models.PositiveIntegerField(default=75, help_text='Target equipment utilization percentage')),
                ('modality_size_estimates', models.JSONField(default=dict, help_text='Average storage size per examination by modality type (in GB)')),
                ('auto_refresh_interval', models.PositiveIntegerField(default=300, help_text='Auto-refresh interval for dashboard in seconds')),
                ('email_notifications', models.BooleanField(default=True, help_text='Enable email notifications for alerts')),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to receive notifications')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Configuration',
                'verbose_name_plural': 'Dashboard Configurations',
            },
        ),
    ]
