# Generated by Django 4.2.6 on 2025-07-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_dashboardconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaan',
            name='content_date',
            field=models.DateField(blank=True, help_text='DICOM ContentDate (0008,0023) - actual examination date', null=True),
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='content_datetime',
            field=models.DateTimeField(blank=True, help_text='Combined DICOM ContentDate and ContentTime for sorting and display', null=True),
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='content_time',
            field=models.TimeField(blank=True, help_text='DICOM ContentTime (0008,0033) - actual examination time', null=True),
        ),
    ]
