# Generated by Django 4.2.6 on 2025-07-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_add_dicom_content_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaan',
            name='content_datetime_source',
            field=models.CharField(blank=True, help_text="Source of the datetime (e.g., 'ContentDate/ContentTime', 'StudyDate/StudyTime')", max_length=50, null=True),
        ),
    ]
