# Generated by Django 4.2.6 on 2025-08-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_add_content_datetime_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacsServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name for the PACS server (e.g., 'Unraid Orthanc', 'Main Hospital PACS')", max_length=100, unique=True)),
                ('orthancurl', models.URLField(help_text='Orthanc server URL (e.g., http://10.0.1.0:8042)', verbose_name='Orthanc URL')),
                ('viewrurl', models.URLField(help_text='DICOM viewer URL for this server', verbose_name='DICOM Viewer URL')),
                ('endpoint_style', models.CharField(choices=[('dicomweb', 'DICOMweb (OHIF-style) - Standard WADO-RS'), ('file', 'File endpoint - Direct Orthanc /file'), ('attachment', 'Attachment - Raw DICOM data'), ('auto', 'Auto-detect - Try best working endpoint')], default='dicomweb', help_text='DICOM endpoint style for image retrieval', max_length=20)),
                ('comments', models.TextField(blank=True, help_text="Purpose and usage notes (e.g., 'This is only for CT Scan images', 'Archive server for studies older than 1 year')")),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this PACS server')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary PACS server for new examinations')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag for servers with historical data')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PACS Server',
                'verbose_name_plural': 'PACS Servers',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='pacsserver',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_primary', True)), fields=('is_primary',), name='unique_primary_pacs'),
        ),
        migrations.AddField(
            model_name='pacsexam',
            name='pacs_server',
            field=models.ForeignKey(blank=True, help_text="PACS server where this examination's DICOM data is stored", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='exam.pacsserver'),
        ),
    ]
