# Generated by Django 4.2.6 on 2025-08-01 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0023_migrate_pacs_config_to_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('media_type', models.CharField(choices=[('CD', 'CD'), ('DVD', 'DVD'), ('XRAY_FILM', 'X-Ray Film'), ('USB', 'USB Drive'), ('DIGITAL_COPY', 'Digital Copy')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of CDs/films')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Collection'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('collected_by', models.CharField(blank=True, help_text='Name of person collecting', max_length=100, null=True)),
                ('collected_by_ic', models.CharField(blank=True, help_text='IC of collector', max_length=25, null=True)),
                ('relationship_to_patient', models.CharField(blank=True, help_text='Relationship to patient', max_length=50, null=True)),
                ('collection_datetime', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, help_text='Special instructions or notes', null=True)),
                ('urgency', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('STAT', 'STAT')], default='NORMAL', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('daftar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_distributions', to='exam.daftar')),
                ('handed_over_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handed_media', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Distribution',
                'verbose_name_plural': 'Media Distributions',
                'ordering': ['-request_date'],
            },
        ),
    ]
