# Generated by Django 4.2.6 on 2025-08-02 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesakit', '0009_pesakit_alamat_pesakit_email_pesakit_telefon_and_more'),
        ('exam', '0024_mediadistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediadistribution',
            name='primary_patient',
            field=models.ForeignKey(blank=True, help_text='Primary patient for this distribution', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_distributions', to='pesakit.pesakit'),
        ),
        migrations.AddField(
            model_name='mediadistribution',
            name='studies',
            field=models.ManyToManyField(help_text='Studies included in this distribution', related_name='media_distributions', to='exam.daftar'),
        ),
        migrations.AlterField(
            model_name='mediadistribution',
            name='daftar',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use studies field instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_media_distributions', to='exam.daftar'),
        ),
    ]
