# Generated by Django 4.2.6 on 2025-08-02 01:20

from django.db import migrations


def populate_media_distribution_fields(apps, schema_editor):
    """Populate new fields from existing data"""
    MediaDistribution = apps.get_model('exam', 'MediaDistribution')
    
    for distribution in MediaDistribution.objects.all():
        if distribution.daftar:
            # Set primary patient from existing daftar
            distribution.primary_patient = distribution.daftar.pesakit
            distribution.save()
            
            # Add the existing daftar to studies
            distribution.studies.add(distribution.daftar)


def reverse_populate_media_distribution_fields(apps, schema_editor):
    """Reverse the population if needed"""
    MediaDistribution = apps.get_model('exam', 'MediaDistribution')
    
    for distribution in MediaDistribution.objects.all():
        distribution.primary_patient = None
        distribution.studies.clear()
        distribution.save()


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_media_distribution_multiple_studies'),
    ]

    operations = [
        migrations.RunPython(
            populate_media_distribution_fields,
            reverse_populate_media_distribution_fields
        ),
    ]
