# Generated by Django 4.2.6 on 2025-08-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_populate_media_distribution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediadistribution',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation', null=True),
        ),
    ]
