# Generated by Django 4.2.6 on 2025-08-02 13:48

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_rejectanalysis_rejectcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectincident',
            name='analysis',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Monthly analysis this incident belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='exam.rejectanalysis'),
        ),
    ]
