# Generated by Django 4.2.6 on 2025-08-03 07:33

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_make_reject_incident_analysis_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectincident',
            name='examination',
            field=auto_prefetch.ForeignKey(blank=True, help_text='The examination that had a reject/retake', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reject_incidents', to='exam.pemeriksaan'),
        ),
    ]
