# Generated by Django 4.2.6 on 2025-08-03 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0030_alter_rejectincident_examination'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectAnalysisTargetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xray_target', models.DecimalField(decimal_places=2, default=8.0, help_text='Target reject rate for X-Ray examinations (default 8%)', max_digits=5, verbose_name='X-Ray Target Rate (%)')),
                ('ct_target', models.DecimalField(decimal_places=2, default=5.0, help_text='Target reject rate for CT examinations (default 5%)', max_digits=5, verbose_name='CT Target Rate (%)')),
                ('mri_target', models.DecimalField(decimal_places=2, default=3.0, help_text='Target reject rate for MRI examinations (default 3%)', max_digits=5, verbose_name='MRI Target Rate (%)')),
                ('ultrasound_target', models.DecimalField(decimal_places=2, default=6.0, help_text='Target reject rate for Ultrasound examinations (default 6%)', max_digits=5, verbose_name='Ultrasound Target Rate (%)')),
                ('mammography_target', models.DecimalField(decimal_places=2, default=4.0, help_text='Target reject rate for Mammography examinations (default 4%)', max_digits=5, verbose_name='Mammography Target Rate (%)')),
                ('overall_target', models.DecimalField(decimal_places=2, default=8.0, help_text='Overall facility target reject rate (default 8%)', max_digits=5, verbose_name='Overall Target Rate (%)')),
                ('drl_compliance_enabled', models.BooleanField(default=True, help_text='Enable Malaysian Diagnostic Reference Level compliance monitoring', verbose_name='DRL Compliance Enabled')),
                ('warning_threshold_multiplier', models.DecimalField(decimal_places=2, default=1.25, help_text='Multiplier for warning threshold (e.g., 1.25 = warning at 125% of target)', max_digits=3, verbose_name='Warning Threshold Multiplier')),
                ('critical_threshold_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for critical threshold (e.g., 1.50 = critical at 150% of target)', max_digits=3, verbose_name='Critical Threshold Multiplier')),
                ('enable_notifications', models.BooleanField(default=True, help_text='Enable email notifications when targets are exceeded', verbose_name='Enable Notifications')),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify when targets are exceeded', verbose_name='Notification Email Addresses')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created these settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_target_settings', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified these settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_target_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reject Analysis Target Settings',
                'verbose_name_plural': 'Reject Analysis Target Settings',
            },
        ),
    ]
