# Generated by Django 4.2.6 on 2025-08-04 18:36

import auto_prefetch
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0032_aigeneratedreport_radiologistreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualRadiologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_history', models.TextField(blank=True, help_text='Clinical history and indication for examination')),
                ('technique', models.TextField(blank=True, help_text='Imaging technique and parameters used')),
                ('findings', models.TextField(help_text='Detailed imaging findings')),
                ('impression', models.TextField(help_text='Clinical impression and diagnosis')),
                ('recommendations', models.TextField(blank=True, help_text='Clinical recommendations and follow-up')),
                ('report_status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('amended', 'Amended')], default='draft', help_text='Current status of the report', max_length=20)),
                ('complexity_level', models.CharField(choices=[('low', 'Low Complexity'), ('medium', 'Medium Complexity'), ('high', 'High Complexity'), ('critical', 'Critical/Emergency')], default='medium', help_text='Complexity level of the case', max_length=20)),
                ('report_start_time', models.DateTimeField(auto_now_add=True, help_text='When report creation started')),
                ('report_completion_time', models.DateTimeField(blank=True, help_text='When report was completed', null=True)),
                ('peer_review_required', models.BooleanField(default=False, help_text='Whether this report requires peer review')),
                ('peer_review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('requires_changes', 'Requires Changes')], default='pending', help_text='Status of peer review', max_length=20)),
                ('peer_review_comments', models.TextField(blank=True, help_text='Peer reviewer comments')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('peer_reviewer', auto_prefetch.ForeignKey(blank=True, help_text='Radiologist performing peer review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_reviewed_manual_reports', to=settings.AUTH_USER_MODEL)),
                ('pemeriksaan', auto_prefetch.ForeignKey(help_text='Examination this report is for', on_delete=django.db.models.deletion.CASCADE, related_name='manual_reports', to='exam.pemeriksaan')),
                ('radiologist', auto_prefetch.ForeignKey(help_text='Radiologist creating this report', on_delete=django.db.models.deletion.CASCADE, related_name='manual_radiology_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Radiology Report',
                'verbose_name_plural': 'Manual Radiology Reports',
                'ordering': ['-created'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='manualradiologyreport',
            constraint=models.UniqueConstraint(fields=('pemeriksaan',), name='unique_manual_report_per_examination'),
        ),
    ]
