# Generated by Django 3.0.3 on 2022-05-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disiplin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disiplin', models.CharField(max_length=50, verbose_name='Disiplin')),
            ],
            options={
                'verbose_name': 'Disiplin',
                'verbose_name_plural': 'Disiplin',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wad', models.CharField(max_length=50, unique=True, verbose_name='Wad')),
                ('disiplin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wad.Disiplin', verbose_name='Disiplin')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
            },
        ),
    ]
