# Generated by Django 3.0.3 on 2022-06-23 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='disiplin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wad.Disiplin', verbose_name='Disiplin'),
        ),
    ]
