# Generated by Django 3.0.3 on 2022-06-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wad', '0002_auto_20220623_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ward',
            options={'select_on_save': True, 'verbose_name': 'Ward', 'verbose_name_plural': 'Wards'},
        ),
    ]
