# Generated by Django 3.0.3 on 2022-06-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wad', '0003_auto_20220623_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ward',
            options={'verbose_name': 'Ward', 'verbose_name_plural': 'Wards'},
        ),
    ]
