# Generated by Django 4.1.2 on 2022-10-29 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wad', '0004_auto_20220623_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='disiplin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wad.disiplin', verbose_name='Disiplin'),
        ),
    ]
