# Generated by Django 4.1.2 on 2022-10-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wad', '0005_alter_ward_disiplin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disiplin',
            name='disiplin',
            field=models.CharField(max_length=50, unique=True, verbose_name='Disiplin'),
        ),
    ]
