# Generated by Django 4.2.6 on 2025-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_jxr_staff_kemaskini_staff_komen'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_supervisor',
            field=models.BooleanField(default=False, help_text='Designates whether the user can access system settings.'),
        ),
    ]
