# Generated by Django 4.2.6 on 2025-07-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_is_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_supervisor',
        ),
    ]
