# Generated by Django 4.2.6 on 2025-08-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_staff_is_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_report',
            field=models.BooleanField(default=False, help_text='User can create and edit radiology reports'),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_view_report',
            field=models.BooleanField(default=True, help_text='User can view radiology reports'),
        ),
    ]
