# Generated by Django 4.2.6 on 2025-08-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_user_id_e8be02_idx',
            old_name='audit_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_resourc_2a3aef_idx',
            old_name='audit_resource_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_2a1328_idx',
            old_name='audit_action_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_timesta_e7a52b_idx',
            old_name='audit_timestamp_success_idx',
        ),
    ]
