# Generated by Django 4.2.6 on 2025-08-10 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomAnnotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('study_instance_uid', models.CharField(db_index=True, help_text='DICOM Study Instance UID', max_length=255)),
                ('series_instance_uid', models.CharField(help_text='DICOM Series Instance UID', max_length=255)),
                ('sop_instance_uid', models.CharField(help_text='DICOM SOP Instance UID', max_length=255)),
                ('image_id', models.TextField(help_text='Cornerstone3D image ID')),
                ('frame_number', models.IntegerField(default=1, help_text='Frame number for multi-frame images')),
                ('annotation_type', models.CharField(choices=[('measurement', 'Measurement'), ('annotation', 'Annotation'), ('arrow', 'Arrow'), ('rectangle', 'Rectangle'), ('ellipse', 'Ellipse'), ('freehand', 'Freehand'), ('angle', 'Angle'), ('bidirectional', 'Bidirectional'), ('length', 'Length'), ('probe', 'Probe'), ('circle', 'Circle'), ('polyline', 'Polyline'), ('spline', 'Spline')], help_text='Type of annotation (measurement, shape, etc.)', max_length=20)),
                ('annotation_data', models.JSONField(help_text='Cornerstone3D annotation data in JSON format')),
                ('label', models.CharField(blank=True, help_text='User-defined label for the annotation', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the annotation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the annotation was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='When the annotation was last modified')),
                ('measurement_value', models.FloatField(blank=True, help_text='Calculated measurement value (length, area, etc.)', null=True)),
                ('measurement_unit', models.CharField(blank=True, help_text='Unit of measurement (mm, cm, px, etc.)', max_length=20)),
                ('user', models.ForeignKey(help_text='User who created this annotation', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DICOM Annotation',
                'verbose_name_plural': 'DICOM Annotations',
                'db_table': 'dicom_annotations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['study_instance_uid'], name='dicom_annot_study_i_4c6873_idx'), models.Index(fields=['user', 'created_at'], name='dicom_annot_user_id_d049ed_idx'), models.Index(fields=['annotation_type'], name='dicom_annot_annotat_3e8a2b_idx'), models.Index(fields=['study_instance_uid', 'image_id'], name='dicom_annot_study_i_d9e975_idx')],
            },
        ),
    ]
