# Generated by Django 4.2.6 on 2025-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomannotation',
            name='cornerstone_annotation_uid',
            field=models.CharField(blank=True, help_text='Cornerstone3D annotation UID for visibility control', max_length=255, null=True),
        ),
    ]
