# Generated by Django 4.2.6 on 2025-08-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_dicomannotation_cornerstone_annotation_uid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dicomannotation',
            constraint=models.UniqueConstraint(condition=models.Q(('cornerstone_annotation_uid__isnull', False)), fields=('cornerstone_annotation_uid',), name='unique_cornerstone_annotation_uid'),
        ),
    ]
