# Generated by Django 4.2.6 on 2025-08-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_dicomannotation_unique_cornerstone_annotation_uid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dicomannotation',
            name='unique_cornerstone_annotation_uid',
        ),
        migrations.RemoveField(
            model_name='dicomannotation',
            name='cornerstone_annotation_uid',
        ),
    ]
