# Generated by Django 4.2.6 on 2023-10-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesakit', '0002_pesakit_jantina_pesakit_umur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesakit',
            name='jantina',
        ),
    ]
