# Generated by Django 4.2.6 on 2023-11-01 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesakit', '0004_pesakit_jan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesakit',
            name='jan',
        ),
    ]
