# Generated by Django 4.2.6 on 2023-11-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesakit', '0006_pesakit_jantan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesakit',
            name='jantan',
        ),
    ]
