# Generated by Django 4.2.6 on 2025-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesakit', '0008_pesakit_jantina'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesakit',
            name='alamat',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='pesakit',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='pesakit',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='pesakit',
            name='catatan',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
